const $=id=>document.getElementById(id),audio=$("audio"),searchInput=$("searchInput"),desktopSearchInput=$("desktopSearchInput"),clearSearch=$("clearSearch"),songList=$("songList"),favoritesList=$("favoritesList"),favoritesEmpty=$("favoritesEmpty"),favoriteCount=$("favoriteCount"),miniCover=$("miniCover"),miniTitle=$("miniTitle"),miniArtist=$("miniArtist"),miniPlay=$("miniPlay"),miniFavorite=$("miniFavorite"),miniProgressBar=$("miniProgressBar"),playerSheet=$("playerSheet"),playerCover=$("playerCover"),playerTitle=$("playerTitle"),playerArtist=$("playerArtist"),sheetFavorite=$("sheetFavorite"),playBtn=$("playBtn"),previousBtn=$("previousBtn"),nextBtn=$("nextBtn"),shuffleBtn=$("shuffleBtn"),repeatBtn=$("repeatBtn"),progress=$("progress"),currentTimeEl=$("currentTime"),durationEl=$("duration"),volume=$("volume");
let songs=[],currentSong=null,shuffle=false,repeat=false,favorites=new Set(JSON.parse(localStorage.getItem("flowmusic:favorites")||"[]"));
const views={home:$("homeView"),search:$("searchView"),library:$("libraryView"),favorites:$("favoritesView")};
function setView(v){v=views[v]?v:"home";Object.entries(views).forEach(([k,e])=>e.classList.toggle("active-view",k===v));document.querySelectorAll("[data-view]").forEach(b=>b.classList.toggle("active",b.dataset.view===v));if(v==="library")renderLibrary();if(v==="favorites")renderFavorites();window.scrollTo({top:0,behavior:"smooth"})}
document.querySelectorAll("[data-view]").forEach(b=>b.onclick=()=>setView(b.dataset.view));document.querySelectorAll("[data-target-view]").forEach(b=>b.onclick=()=>setView(b.dataset.targetView));$("heroLibraryBtn").onclick=()=>setView("library");
const key=s=>s?.id||s?.url||"",isFav=s=>favorites.has(key(s)),fmt=s=>!Number.isFinite(s)?"0:00":`${Math.floor(s/60)}:${Math.floor(s%60).toString().padStart(2,"0")}`;
function esc(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
function query(){return(searchInput.value||desktopSearchInput.value||"").trim().toLowerCase()}function match(s,q){return!q||[s.title,s.artist,s.album].filter(Boolean).some(v=>String(v).toLowerCase().includes(q))}
async function loadLibrary(){try{let r=await fetch("./api/songs",{cache:"no-store"});if(!r.ok)throw 0;songs=await r.json();$("desktopServerStatus").textContent="Verbonden"}catch{songs=[];$("desktopServerStatus").textContent="Nog niet gekoppeld"}renderLibrary();renderFavorites()}
function row(song){let b=document.createElement("button");b.className="song-row";b.innerHTML=`<img class="song-thumb" src="${esc(song.cover||"./default-cover.svg")}" alt=""><span class="song-text"><strong>${esc(song.title||"Onbekende titel")}</strong><span>${esc(song.artist||"Onbekende artiest")}${song.album?" • "+esc(song.album):""}</span></span><span class="row-heart ${isFav(song)?"on":""}">${isFav(song)?"♥":"♡"}</span>`;b.onclick=e=>{if(e.target.closest(".row-heart"))toggleFav(song);else playSong(song)};return b}
function renderLibrary(){let list=songs.filter(s=>match(s,query()));songList.innerHTML="";$("emptyState").classList.toggle("hidden",list.length>0);list.forEach(s=>songList.appendChild(row(s)))}function renderFavorites(){let list=songs.filter(isFav);favoritesList.innerHTML="";favoritesEmpty.classList.toggle("hidden",list.length>0);favoriteCount.textContent=`${list.length} ${list.length===1?"nummer":"nummers"}`;list.forEach(s=>favoritesList.appendChild(row(s)))}
function toggleFav(s){if(!s)return;let k=key(s);favorites.has(k)?favorites.delete(k):favorites.add(k);localStorage.setItem("flowmusic:favorites",JSON.stringify([...favorites]));syncFav();renderLibrary();renderFavorites()}
function syncFav(){let on=currentSong&&isFav(currentSong);miniFavorite.textContent=on?"♥":"♡";sheetFavorite.textContent=on?"♥":"♡";miniFavorite.style.color=on?"var(--accent)":"";sheetFavorite.style.color=on?"var(--accent)":""}
function syncNow(){let c=currentSong?.cover||"./default-cover.svg",t=currentSong?.title||"Geen nummer geselecteerd",a=currentSong?.artist||"FlowMusic";miniCover.src=playerCover.src=c;miniTitle.textContent=playerTitle.textContent=t;miniArtist.textContent=playerArtist.textContent=a;syncFav()}
function playSong(s){if(!s)return;currentSong=s;audio.src=s.url;audio.play().catch(()=>{});syncNow();if("mediaSession"in navigator)navigator.mediaSession.metadata=new MediaMetadata({title:s.title||"",artist:s.artist||"",album:s.album||"",artwork:[{src:s.cover||"./default-cover.svg"}]})}
function visible(){return songs.filter(s=>match(s,query()))}function next(){let l=visible();if(!l.length)return;if(shuffle){let p=l.filter(s=>key(s)!==key(currentSong));return playSong(p[Math.floor(Math.random()*p.length)]||l[0])}let i=l.findIndex(s=>key(s)===key(currentSong));playSong(l[(i+1+l.length)%l.length])}function prev(){let l=visible();if(!l.length)return;let i=l.findIndex(s=>key(s)===key(currentSong));playSong(l[(i-1+l.length)%l.length])}function togglePlay(){if(!currentSong){let l=visible();if(l.length)playSong(l[0]);return}audio.paused?audio.play():audio.pause()}
miniPlay.onclick=playBtn.onclick=togglePlay;previousBtn.onclick=prev;nextBtn.onclick=next;miniFavorite.onclick=sheetFavorite.onclick=()=>toggleFav(currentSong);shuffleBtn.onclick=()=>{shuffle=!shuffle;shuffleBtn.classList.toggle("active",shuffle)};repeatBtn.onclick=()=>{repeat=!repeat;repeatBtn.classList.toggle("active",repeat)};
audio.onplay=()=>{miniPlay.textContent=playBtn.textContent="⏸"};audio.onpause=()=>{miniPlay.textContent=playBtn.textContent="▶"};audio.ontimeupdate=()=>{if(!audio.duration)return;let p=audio.currentTime/audio.duration*100;progress.value=p;miniProgressBar.style.width=p+"%";currentTimeEl.textContent=fmt(audio.currentTime);durationEl.textContent=fmt(audio.duration)};audio.onloadedmetadata=()=>durationEl.textContent=fmt(audio.duration);audio.onended=()=>{if(repeat&&currentSong){audio.currentTime=0;audio.play()}else next()};progress.oninput=()=>{if(audio.duration)audio.currentTime=+progress.value/100*audio.duration};volume.oninput=()=>audio.volume=+volume.value;audio.volume=+volume.value;
function openSheet(){playerSheet.classList.add("open");playerSheet.setAttribute("aria-hidden","false");document.body.style.overflow="hidden"}function closeSheet(){playerSheet.classList.remove("open");playerSheet.setAttribute("aria-hidden","true");document.body.style.overflow=""}$("openPlayer").onclick=openSheet;$("closePlayer").onclick=closeSheet;playerSheet.querySelector(".backdrop").onclick=closeSheet;let sy=0;playerSheet.querySelector(".sheet-card").addEventListener("touchstart",e=>sy=e.touches[0].clientY,{passive:true});playerSheet.querySelector(".sheet-card").addEventListener("touchend",e=>{if(e.changedTouches[0].clientY-sy>90)closeSheet()},{passive:true});
function syncSearch(src){let v=src.value;if(src!==searchInput)searchInput.value=v;if(src!==desktopSearchInput)desktopSearchInput.value=v;clearSearch.classList.toggle("hidden",!v);if(v.trim())setView("library");renderLibrary()}searchInput.oninput=()=>syncSearch(searchInput);desktopSearchInput.oninput=()=>syncSearch(desktopSearchInput);clearSearch.onclick=()=>{searchInput.value=desktopSearchInput.value="";clearSearch.classList.add("hidden");renderLibrary();searchInput.focus()};
if("mediaSession"in navigator){navigator.mediaSession.setActionHandler("play",()=>audio.play());navigator.mediaSession.setActionHandler("pause",()=>audio.pause());navigator.mediaSession.setActionHandler("previoustrack",prev);navigator.mediaSession.setActionHandler("nexttrack",next)}if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("./service-worker.js").catch(()=>{}));loadLibrary();
